In [1]:
from ROOT import TLorentzVector
from ROOT import Math
import numpy as np

Welcome to JupyROOT 6.22/06


In [8]:
def thetaPhi():
    '''returns random theta and phi values'''
    theta = np.random.uniform(0,2*np.pi)
    phi = np.random.uniform(0,np.pi)
    return theta, phi

def momenta(mag, theta, phi):
    '''given an input magnitude, theta and phi the cartesian momenta are returned'''
    Px = mag * np.sin(theta) * np.cos(phi) 
    Py = mag * np.sin(theta) * np.sin(phi)
    Pz = mag * np.cos(theta)
    
    return Px, Py, Pz

def vector(g, theta, phi, mag, mass):
    '''given a tlorentzvector g the cartesian components are set with the circular components and the mass'''
    Px, Py, Pz = momenta(mag, theta, phi)
    g.SetPxPyPzE(Px, Py, Pz, mass)
    
    
def boost(px, py, pz, e, beta):
    '''input 4 momenta of particle wanted to be boosted, and beta the ratio v/c which it is boosted by
    returns the new boosted 4 momenta'''
    #initialising arrays for boosted momenta
    boostx = np.zeros([len(px)])
    boosty = np.zeros([len(px)])
    boostz = np.zeros([len(px)])
    booste = np.zeros([len(px)])
    
    #looping over momenta values   
    for i in range(len(px)):
        vec = Math.LorentzVector('ROOT::Math::PxPyPzE4D<double>')(px[i], py[i], pz[i], e[i]) #using this type of lorentzvec works better
        boost = Math.VectorUtil.boostZ(vec, beta) # boosting by factor beta
        #components from the boosted lorentzvector are appended to arrays for momenta
        boostx[i], boosty[i], boostz[i], booste[i] = boost.Px(), boost.Py(), boost.Pz(), boost.E()
        
        
    return boostx,boosty,boostz,booste

def momentaArr(px, py, pz, e):
    '''inputs the arrays of each momemtum component and returns them as a single array with all compoents'''
    momenta = np.zeros([len(px),4])
    for i in range(len(px)):
        momenta[i,0] = px[i]
        momenta[i,1] = py[i]
        momenta[i,2] = pz[i]
        momenta[i,3] = e[i]
        
    return momenta

def wArr(num):
    '''just for making numpy array of stationary w given the number of events'''
    momenta = np.zeros([num,4])
    momenta[:,3] = wMass
    
    return momenta

In [3]:
print(momenta(80, 0.6, 0.5))

(39.64163106833054, 21.656321754097934, 66.02684919277426)


In [4]:
#defining mass of particles (all in GeV/c^2)
wMass = 80.3

eMass = 0.0005

nMass = 0

# equations for this bit found here: http://www.phys.ufl.edu/~avery/course/4390/f2015/lectures/relativistic_kinematics_2.pdf

eE = (wMass**2 + eMass**2)/(2*wMass) # energy of the electron

mag = np.sqrt(eE**2 - eMass**2) # momentum magnitude 

print(mag)

# setting up particles
w = TLorentzVector()
#stationary w
w.SetPxPyPzE(0,0,0, wMass)

e = TLorentzVector()
n = TLorentzVector()


40.149999998443334


In [5]:
 def components(num):
    '''given a number of events wanted, returns arrays of the components of the electron and neutrinos
    in the frame of the wboson'''
    
    #initialising arrays for components
    ePx = np.zeros(num)
    ePy = np.zeros(num)
    ePz = np.zeros(num)
    eE = np.zeros(num)

    nPx = np.zeros(num)
    nPy = np.zeros(num)
    nPz = np.zeros(num)
    nE = np.zeros(num)
    
    # looping over number of events and filling component arrays
    for i in range(num):
        #making e components
        thetae, phie = thetaPhi()
        vector(e, thetae, phie, mag, wMass/2)
        
        ePx[i] = e.Px()
        ePy[i] = e.Py()
         m[i] = e.Pz()
        eE[i] = e.E()
               
        #making neutrino components
        n = w - e
        #n.SetE(nMass)
               
        nPx[i] = n.Px()
        nPy[i] = n.Py()
        nPz[i] = n.Pz()
        nE[i] = n.E()
        
    return ePx, ePy, ePz, eE, nPx, nPy, nPz, nE


In [13]:
# making num events worth of components
num = 10
ePx, ePy, ePz, eE, nPx, nPy, nPz, nE = components(num)
wArray =  wArr(num)
wPx, wPy, wPz, wE = wArray[:,0], wArray[:,1], wArray[:,2], wArray[:,3] 

beta = 0.1

#applying the boost to the particles 
wPx, wPy, wPz, wE = boost(wPx, wPy, wPz, wE, beta)
ePx, ePy, ePz, eE = boost(ePx, ePy, ePz, eE, beta)
nPx, nPy, nPz, nE = boost(nPx, nPy, nPz, nE, beta)

#putting momentas into arrays
wArray = momentaArr(wPx, wPy, wPz, wE)
eArr = momentaArr(ePx, ePy, ePz, eE)
nArr = momentaArr(nPx, nPy, nPz, nE)

In [15]:
print(eArr[0])
print(nArr[0])
print(wArray)

[ 36.72802525  -2.40983846 -12.08513295  38.7402323 ]
[-36.72802525   2.40983846  20.15558661  41.96430426]
[[ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]
 [ 0.          0.          8.07045366 80.70453657]]


this bit is just some testing and can be ignored:

In [ ]:
#checking to see the boost function has worked properly on the e and n
e.SetPxPyPzE(ePx[0], ePy[0], ePz[0], eE[0])
n.SetPxPyPzE(nPx[0], nPy[0], nPz[0], nE[0])

v = TLorentzVector()
v = e + n

print(v.E())

wmath = Math.LorentzVector('ROOT::Math::PxPyPzE4D<double>')(0,0,0,wMass)

beta = 0.1 # ratio v/c which z component of w is boosted by

wBoost = Math.VectorUtil.boostZ(wmath, beta)
print(wBoost)
w.SetPxPyPzE(wBoost.Px(), wBoost.Py(),wBoost.Pz(),wBoost.E())

b = e.BoostVector()
wb = Math.LorentzVector('ROOT::Math::PxPyPzE4D<double>')(w.Px(),w.Py(),w.Pz(),w.E())

wboo = Math.VectorUtil.boost(wb, b)

print(wboo)